### ISSUE TITLE
Jak dodać i zainstalować ręcznie MediaInfo z FanPack aby pojawił się pod PPM przy materiałach wideo?

### ISSUE THREAD

**Issue by RemixPL1994** [potplayer-fanpack/FanPack_Lite#2]
Jak dodać i zainstalować ręcznie MediaInfo z FanPack aby pojawił się pod PPM przy materiałach wideo?

![obraz](https://user-images.githubusercontent.com/52541621/228284059-ad573067-0df6-499c-bb20-59d9c5932346.png)

![obraz](https://user-images.githubusercontent.com/52541621/228284206-d72c953b-66b0-4c75-9ee1-83f89cbbe489.png)

Konkretnie razem z  tym:

![obraz](https://user-images.githubusercontent.com/52541621/228289758-18b31505-f7c6-4300-9f1c-5f5ed1a55e28.png)

![obraz](https://user-images.githubusercontent.com/52541621/228290106-04eeb447-f6bf-47e1-9299-1e004826bab5.png)

Co powinienem pobrać i zainstalować oraz jakie ustawienie w rejestrze powinno pojawić się aby działało to w ten sam sposób i wyglądało gdy zainstaluje się właśnie to razem z instalatorem FanPacka?

**Comment by potplayer-fanpack** [comment]
W FanPacku instalacja MI jest rozwiązana w ten sposób, że w komponentach należy go zaznaczyć - wtedy będzie widoczna opcja instalacji w dodatkowych zadaniach, jeśli był zainstalowany wcześniej (również jeśli zostały komponenty po deinstalacji), to nie będzie widoczny w komponentach.

Pliki potrzebne do poprawnego działania znajdują się w folderze src >> x64 >> Module >> MI.

Opcje instalacji w rejestrze znajdują się w skrypcie instalacji FanPacka:

```
Root: HKCU; Subkey: "Software\MediaInfo"; ValueName: "Path"; ValueType: String; ValueData: "{commonpf}\DAUM\PotPlayer\Module\MI\";                                  Tasks: "minfo1"; Flags: uninsdeletevalue uninsdeletekeyifempty 
Root: HKCU; Subkey: "Software\Classes\*\shell\MediaInfo"; ValueName: "Icon"; ValueType: String; ValueData: """{commonpf}\DAUM\PotPlayer\Module\MI\mediainfo.exe"""; Tasks: "minfo1"; Flags: uninsdeletevalue uninsdeletekeyifempty 
Root: HKCU; Subkey: "Software\Classes\*\shell\MediaInfo\Command"; ValueType: String; ValueData: """{commonpf}\DAUM\PotPlayer\Module\MI\mediainfo.exe"" ""%1""";     Tasks: "minfo1"; Flags: uninsdeletevalue uninsdeletekeyifempty 
```

Możesz powyższe dane wprowadzić do rejestru spod palca -> **commonpf** to C:\Program Files
