### ISSUE TITLE
Sugestia / Prośba - Dodać możliwość w aktualizacji i przyszłym instalatorze FanPack v1.1.86 wybór czy ma instalować dekodery MPC.

### ISSUE THREAD

**Issue by RemixPL1994** [potplayer-fanpack/FanPack_Lite#3]
Sugestia / Prośba - Dodać możliwość w aktualizacji i przyszłym instalatorze FanPack v1.1.86 wybór czy ma instalować dekodery MPC:

![obraz](https://user-images.githubusercontent.com/52541621/228287178-5919fa5a-797e-4902-8236-e32d9eb122d2.png)

Aktualnie w instalatorze nie ma żadnego wyboru czy mają być one instalowane czy też nie.

Wiem, że zniknęły wyboru profili tzn CUDA, Intel, AMD itd i już zostało to wyjaśnione z jakiego względu i jest to jasne.

Ale jednak przydało by się aby powstał wybór instalacji dodatkowych dekoderów MPC i każdy kto będzie chciał to je po prostu zainstaluje, a ten kto nie chcę zaznaczy aby nie były instalowane razem z FanPackiem,

Z tego co widzę w FanPack v1.1.85 występuje taki wybór w rendererze czy ma go instalować czy nie:

![obraz](https://user-images.githubusercontent.com/52541621/228288406-5c440a1b-06ac-420c-8205-83cc28f90b5b.png)

I według mnie to jest najlepsza opcja.

Było by miło gdyby taka sama obsługa została wprowadzona dla wyboru dekoderów MPC.

W tym momencie obojętnie co zaznaczymy w instalatorze te dekodery MPC są instalowane zawsze. 

Wiem, że one nie zajmują dużo miejsca na dysku i nie przeszkadzają po instalacji jeśli nie są ustawione i nie są używane konkretnie ale dla mnie są instalowane zbędnie stąd ta propozycja i prośba ode mnie.

**Comment by potplayer-fanpack** [comment]
Zobaczymy, na razie czekam na nową wersję PotPlayer'a (co będzie pewnie na początku kwietnia, jeszcze przed świętami) i pełną stabilizację nazewnictwa folderów i plików.

**Comment by potplayer-fanpack** [comment]
Jeszcze odnośnie splitterów MPC; są one aktywne zawsze (preferowane), a używane są dlatego, gdyż lepiej spisują się podczas odtwarzania. Szczególnie sprawdziły się podczas odtwarzania z YT, więc prawdopodobnie zostanie tak jak jest. Chyba, że... podczas testów znikną problemy z natywnymi splitterami, wtedy w ogóle wycofam te MPC.
