### ISSUE TITLE
Problem z odtwarzaniem plików mkv

### ISSUE THREAD

**Issue by antek821** [potplayer-fanpack/FanPack_Lite#4]
Na wstępie chciałbym Ci Adamie (@potplayer-fanpack)  serdecznie podziękować za Twoją pracę nad wszelkimi tłumaczeniami oraz rozwojem FanPacka już od tak wielu lat, a z okazji nowego roku pragnę życzyć Ci dużo zdrowia oraz wszelkiej pomyślności!

Wiem, że repozytorium dotyczy wersji Lite, ale chciałbym zgłosić problem ze zwykłą wersją FanPacka64, który zauważyłem dzisiaj po "czystej" instalacji FanPacka64.

Do rzeczy:
Po aktywacji profilu `DXVA Native Decoder`, nie byłem w stanie odtworzyć kilku plików `mkv` z komputera. Dla porównania spróbowałem również czegoś ogólnodostępnego z Internetu: https://filesamples.com/samples/video/mkv/sample_1280x720_surfing_with_audio.mkv, ze strony: https://filesamples.com/formats/mkv. Screenshoty poniżej są właśnie z wykorzystaniem tego pliku.

Po odpaleniu pliku w wyżej wymienionym profilu, dźwięk odtwarzany jest w porządku, natomiast obraz to jednolita czerń, PotPlayer zaczyna się zacinać, a przy próbie zatrzymania odtwarzania całkowicie przestaje odpowiadać i musiałem ubijać proces ręcznie. Udało mi się natomiast zrobić zrzut informacji o odtwarzaniu:
![image_2024-01-01_21-08-42](https://github.com/potplayer-fanpack/FanPack_Lite/assets/77172951/29bbef80-5c9b-4272-adcc-c6657d0bcbff)

Po szybkim dochodzeniu udało mi się znaleźć rozwiązanie:
W ustawieniach: `Dekodery/filtry` -> `Globalne priorytety filtrów` -> `Zarządzanie niestandardowymi filtrami`
odznaczyłem widoczny tam `AviSynth Filter` i zapisałem ustawienia:
![image_2024-01-01_21-10-00](https://github.com/potplayer-fanpack/FanPack_Lite/assets/77172951/1854caa7-4b83-4c97-aea9-cc61ded2455c)

Po tym zabiegu wideo odtwarzane jest bez najmniejszych problemów:
![image_2024-01-01_21-09-39](https://github.com/potplayer-fanpack/FanPack_Lite/assets/77172951/e0a19ce5-b654-4048-bca2-37383e047ea5)

Jak wspomniałem na początku: problem jest u mnie powtarzalny na wielu różnych plikach `mkv`, i wydaje się że ten globalny filtr powoduje problemy przy próbie wykorzystania DXVA Native, więc może nie powinien być on dodany globalnie, tak aby w profilu `DXVA Native Decoder` - oraz ewentualnie w profilu domyślnym - nie stwarzał problemów?

**Comment by potplayer-fanpack** [comment]
Dzięki za życzenia noworoczne, z wzajemnością życzę Ci tego samego.

Dzięki za info o konflikcie filtra avs z profilem Native DXVA. Postaram się rozwiązać go jak najszybciej, jak czas pozwoli to jeszcze dzisiaj będzie nowa wersja.

**Comment by antek821** [comment]
Widzę że jest już nowa wersja, Dziękuję za ekspresową poprawkę. Zamykam temat 😉
