### ISSUE TITLE
Nie działająca stona 

### ISSUE THREAD

**Issue by Kaktusik234** [potplayer-fanpack/FanPack_Lite#5]
Cześć, może nie powinienem tego pisać tutaj, ale nie wiedziałem, w jaki inny sposób się z tobą skontaktować. Przechodząc do mojego pytania dlaczego nie działa twoja strona internetowa? Gdy wchodzę na stronę http://www.potplayerclub.pl/
, nie ma nic oprócz białej strony na telefonie. Gdy wchodzę na stronę, mam granatową stronę z napisem potplayerclub.pl

**Comment by potplayer-fanpack** [comment]
Cześć, strona już nie istnieje. [Tutaj](https://portable.info.pl/potplayer-portable/) powinna być jeszcze informacja, która wisiała ponad miesiąc na mojej stronie, dlaczego jej już nie ma.

**Comment by Kaktusik234** [comment]
Dziękuję za informację zwrotną i wyjaśnienie braku strony internetowej. Pozdrawiam.
